# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20180525_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teaching_assistants',
            field=models.ManyToManyField(blank=True, related_name='teaching_assistant', to=settings.AUTH_USER_MODEL),
        ),
    ]
