# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_quiz_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='first_option',
            field=models.TextField(verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='fourth_option',
            field=models.TextField(verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='second_option',
            field=models.TextField(verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='third_option',
            field=models.TextField(verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_of_submission',
            field=models.DateTimeField(help_text='Date and time of submission'),
        ),
    ]
