# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20180531_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
