# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180524_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('AD', 'System Admin'), ('LA', 'LMS Admin'), ('IN', 'Instructor'), ('TA', 'Teaching Assistant'), ('ST', 'Student')], max_length=2),
        ),
    ]
