# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180525_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('create_lms_admin', 'Create LMS Admin'), ('create_instructor', 'Create Instructor'), ('create_teaching_assistant', 'Create Teaching Assistant'), ('create_student', 'Create Student'))},
        ),
    ]
