# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20180521_1519'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='lmsadmin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('IN', 'Instructor'), ('ST', 'Student')], default='AD', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='LMSAdmin',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
