# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180521_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('LA', 'Admin'), ('IN', 'Instructor'), ('ST', 'Student')], max_length=2),
        ),
    ]
