# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('class_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.TextField()),
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('grade', models.CharField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F')], max_length=1, null=True)),
                ('syllabus', models.TextField()),
                ('content', models.ManyToManyField(to='classroom.Content')),
                ('instructors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instructor')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('comments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Comments')),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('comments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Comments')),
                ('content', models.ManyToManyField(to='classroom.Content')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='comments',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.Comments'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='content',
            field=models.ManyToManyField(to='classroom.Content'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Instructor'),
        ),
    ]
