# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20180529_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
