# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20180529_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='comment',
            field=models.ManyToManyField(to='classroom.Comments'),
        ),
    ]
