# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20180530_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Quiz',
            new_name='QuizOrAssignment',
        ),
    ]
