# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20180530_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizorassignment',
            name='comment',
            field=models.ManyToManyField(blank=True, to='classroom.Comment'),
        ),
    ]
