# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_auto_20180531_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.SmallIntegerField(default=0),
        ),
    ]
