# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_auto_20180602_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.AlterModelOptions(
            name='quizorassignment',
            options={'permissions': (('modify_quiz_or_assignment', 'Modify quiz or assignment'),)},
        ),
    ]
