# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0018_auto_20180608_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='quiz',
            new_name='quiz_or_assignment',
        ),
    ]
